<a href="https://colab.research.google.com/github/ovisaha5/DataProcessingSP22/blob/main/Quiz3_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Quiz3
###Avijit Saha

In [1]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

#####Navigating Data and The Entries

In [8]:
%%bigquery --project smart-tracer-338719
SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
LIMIT 7

      trip_id  ... duration_minutes
0  9900289692  ...               39
1  9900285987  ...               31
2  9900285989  ...               31
3  9900285991  ...               30
4  9900286140  ...               19
5  9900286143  ...               17
6  9900286171  ...                6

[7 rows x 9 columns]

In [7]:
%%bigquery --project smart-tracer-338719
SELECT 
  COUNT(*) as total_rows
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`

   total_rows
0     1424786

#####Longest Trip

In [17]:
%%bigquery --project smart-tracer-338719
SELECT 
  MAX(duration_minutes) as longest_trip_duration_minutes
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`

   longest_trip_duration_minutes
0                          34238

#####Average Duration for Trip

In [16]:
%%bigquery --project smart-tracer-338719
SELECT 
  AVG(duration_minutes) as avg_duration_minutes
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`

   avg_duration_minutes
0             30.870428