<a href="https://colab.research.google.com/github/ovisaha5/DataProcessingSP22/blob/main/Quiz_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Quiz 17 Integers and Floats
####Avijit Saha

In [9]:
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/nurfnick/Data_Viz/main/iris.csv')
df

     SepalLength  SepalWidth  PedalLength  PedalWidth           Class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

#####Identifying the greater mean with float or integer

In [10]:
df.SepalLength.mean()

5.843333333333335

In [11]:
df.SepalLength=df.SepalLength.astype('int')
df

     SepalLength  SepalWidth  PedalLength  PedalWidth           Class
0              5         3.5          1.4         0.2     Iris-setosa
1              4         3.0          1.4         0.2     Iris-setosa
2              4         3.2          1.3         0.2     Iris-setosa
3              4         3.1          1.5         0.2     Iris-setosa
4              5         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145            6         3.0          5.2         2.3  Iris-virginica
146            6         2.5          5.0         1.9  Iris-virginica
147            6         3.0          5.2         2.0  Iris-virginica
148            6         3.4          5.4         2.3  Iris-virginica
149            5         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [12]:
df.SepalLength.mean()

5.386666666666667

So, the integer decrease the mean.

#####Direction of the shift with GROUPBY Class

In [25]:
df.groupby('Class')
df

     SepalLength  SepalWidth  PedalLength  PedalWidth           Class
0              5         3.5          1.4         0.2     Iris-setosa
1              4         3.0          1.4         0.2     Iris-setosa
2              4         3.2          1.3         0.2     Iris-setosa
3              4         3.1          1.5         0.2     Iris-setosa
4              5         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145            6         3.0          5.2         2.3  Iris-virginica
146            6         2.5          5.0         1.9  Iris-virginica
147            6         3.0          5.2         2.0  Iris-virginica
148            6         3.4          5.4         2.3  Iris-virginica
149            5         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

Yes, the Shifting remain same if I groupby Class.

####Gathering the mean, median, count and standard deviation of all column

In [26]:
df.groupby('Class').agg(['mean','median','count', 'std'])

                SepalLength               ... PedalWidth
                       mean median count  ...     median count       std
Class                                     ...
Iris-setosa            4.60    5.0    50  ...        0.2    50  0.107210
Iris-versicolor        5.48    5.0    50  ...        1.3    50  0.197753
Iris-virginica         6.08    6.0    50  ...        2.0    50  0.274650

[3 rows x 16 columns]