<a href="https://colab.research.google.com/github/ovisaha5/DataProcessingSP22/blob/main/Quiz2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quiz 2
## Avijit Saha

#### Importing libraries

In [4]:
import pandas as pd

#### Loading Irish Dataset

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/nurfnick/Data_Viz/main/iris.csv')

df

     SepalLength  SepalWidth  PedalLength  PedalWidth           Class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

#### Calling A Column

In [7]:
df[['SepalLength']]

     SepalLength
0            5.1
1            4.9
2            4.7
3            4.6
4            5.0
..           ...
145          6.7
146          6.3
147          6.5
148          6.2
149          5.9

[150 rows x 1 columns]

Find Mean

In [10]:
df.SepalLength.mean()

5.843333333333335

#### Last Row

In [9]:
df.iloc[-1]

SepalLength               5.9
SepalWidth                  3
PedalLength               5.1
PedalWidth                1.8
Class          Iris-virginica
Name: 149, dtype: object

#### Melt the Data

In [17]:
df_melt = df.melt(id_vars = 'Class',
                  value_vars = ['SepalLength','PedalLength'],
                  var_name = 'colmuns')
df_melt.tail()

              Class      colmuns  value
295  Iris-virginica  PedalLength    5.2
296  Iris-virginica  PedalLength    5.0
297  Iris-virginica  PedalLength    5.2
298  Iris-virginica  PedalLength    5.4
299  Iris-virginica  PedalLength    5.1

In [28]:
df_melt.pivot(columns = 'colmuns', values = ['value', 'Class'])

              value                       Class
colmuns PedalLength SepalLength     PedalLength  SepalLength
0               NaN         5.1             NaN  Iris-setosa
1               NaN         4.9             NaN  Iris-setosa
2               NaN         4.7             NaN  Iris-setosa
3               NaN         4.6             NaN  Iris-setosa
4               NaN           5             NaN  Iris-setosa
..              ...         ...             ...          ...
295             5.2         NaN  Iris-virginica          NaN
296               5         NaN  Iris-virginica          NaN
297             5.2         NaN  Iris-virginica          NaN
298             5.4         NaN  Iris-virginica          NaN
299             5.1         NaN  Iris-virginica          NaN

[300 rows x 4 columns]

####Select Flower

In [40]:
df.query('PedalLength >5 and SepalLength <7')

     SepalLength  SepalWidth  PedalLength  PedalWidth            Class
83           6.0         2.7          5.1         1.6  Iris-versicolor
100          6.3         3.3          6.0         2.5   Iris-virginica
101          5.8         2.7          5.1         1.9   Iris-virginica
103          6.3         2.9          5.6         1.8   Iris-virginica
104          6.5         3.0          5.8         2.2   Iris-virginica
108          6.7         2.5          5.8         1.8   Iris-virginica
110          6.5         3.2          5.1         2.0   Iris-virginica
111          6.4         2.7          5.3         1.9   Iris-virginica
112          6.8         3.0          5.5         2.1   Iris-virginica
114          5.8         2.8          5.1         2.4   Iris-virginica
115          6.4         3.2          5.3         2.3   Iris-virginica
116          6.5         3.0          5.5         1.8   Iris-virginica
120          6.9         3.2          5.7         2.3   Iris-virginica
124          6.7         3.3          5.7         2.1   Iris-virginica
128          6.4         2.8          5.6         2.1   Iris-virginica
132          6.4         2.8          5.6         2.2   Iris-virginica
133          6.3         2.8          5.1         1.5   Iris-virginica
134          6.1         2.6          5.6         1.4   Iris-virginica
136          6.3         3.4          5.6         2.4   Iris-virginica
137          6.4         3.1          5.5         1.8   Iris-virginica
139          6.9         3.1          5.4         2.1   Iris-virginica
140          6.7         3.1          5.6         2.4   Iris-virginica
141          6.9         3.1          5.1         2.3   Iris-virginica
142          5.8         2.7          5.1         1.9   Iris-virginica
143          6.8         3.2          5.9         2.3   Iris-virginica
144          6.7         3.3          5.7         2.5   Iris-virginica
145          6.7         3.0          5.2         2.3   Iris-virginica
147          6.5         3.0          5.2         2.0   Iris-virginica
148          6.2         3.4          5.4         2.3   Iris-virginica
149          5.9         3.0          5.1         1.8   Iris-virginica

#### Group The Data

In [41]:
df.groupby(by = 'Class').agg(['mean','median'])

                SepalLength        SepalWidth  ... PedalLength PedalWidth
                       mean median       mean  ...      median       mean median
Class                                          ...
Iris-setosa           5.006    5.0      3.418  ...        1.50      0.244    0.2
Iris-versicolor       5.936    5.9      2.770  ...        4.35      1.326    1.3
Iris-virginica        6.588    6.5      2.974  ...        5.55      2.026    2.0

[3 rows x 8 columns]